name: Build and Deploy with Codacy

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: node:16-alpine

    steps:
      - name: Install git and rsync
        run: |
          apk update && apk add git rsync
        working-directory: ../
      - name: Configure git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global --add safe.directory /__w/peter-98.github.io/github-pages-deploy-action-temp-deployment-folder
        working-directory: ../
      - uses: actions/checkout@v2
      - name: Install Ionic
        run: npm install -g @ionic/cli
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Build Ionic project
        run: |
          ionic build --prod -- --base-href http://pedromrtaguilera.tech/
          cp www/index.html www/404.html
      - uses: actions/upload-artifact@v3
        with:
          name: www
          path: www/
      - name: Install Codacy coverage script
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh)
      - name: Run tests and generate coverage report
        run: npm run tests -- --single-run --reporters progress,coverage
      - name: Upload coverage report to Codacy
        run: |
          npm install -g codacy-coverage-reporter
          codacy-coverage-reporter report -l <cobertura|lcov> -r ./coverage/report.xml
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        if: contains(github.ref,'refs/heads/master')
        with:
          branch: gh-pages
          folder: www
          clean: true
