name: Build and Deploy

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: node:16-alpine

    steps:
      - name: Install git and rsync
        run: |
          apk update && apk add git rsync
        working-directory: ../

      - name: Configure git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global --add safe.directory /__w/peter-98.github.io/github-pages-deploy-action-temp-deployment-folder
        working-directory: ../

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - uses: actions/checkout@v2

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Install Puppeteer dependencies
        run: apk add --no-cache chromium

      - name: Set Puppeteer environment variables
        run: |
          echo "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true" >> $GITHUB_ENV
          echo "CHROME_BIN=/usr/bin/google-chrome-stable" >> $GITHUB_ENV

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Install Google Chrome
        run: |
          apt-get update
          apt-get install -y wget
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
          apt-get update
          apt-get install -y google-chrome-stable

      - name: Set Chrome SUID Sandbox
        run: |
          echo "sudo chown root:root /usr/libexec/chrome-sandbox" >> $GITHUB_ENV
          echo "sudo chmod 4755 /usr/libexec/chrome-sandbox" >> $GITHUB_ENV

      - name: Build Ionic project
        run: |
          ionic build --prod -- --base-href http://pedromrtaguilera.tech/
          cp www/index.html www/404.html

      - name: Run tests and generate coverage report
        run: ng test --no-watch --code-coverage --browsers=Chrome

      - name: Upload coverage report to Codacy
        run: |
          npm install -g codacy-coverage-reporter
          codacy-coverage-reporter report -l lcov -r ./coverage/app/lcov.info
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

      - uses: actions/upload-artifact@v3
        with:
          name: www
          path: www/

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        if: contains(github.ref,'refs/heads/master')
        with:
          branch: gh-pages
          folder: www
          clean: true
