name: Build and Deploy 

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: node:16-alpine

    steps:
      - name: Install git and rsync
        run: |
          apk update && apk add git rsync
        working-directory: ../
      - name: Configure git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global --add safe.directory /__w/peter-98.github.io/github-pages-deploy-action-temp-deployment-folder
        working-directory: ../
      - uses: actions/checkout@v2
      - name: Install Ionic
        run: npm install -g @ionic/cli
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          output: results.sarif
          format: sarif
          # Adjust severity of non-security issues
          gh-code-scanning-compat: true
          # Force 0 exit code to allow SARIF file generation
          # This will hand over control about PR rejection to the GitHub side
          max-allowed-issues: 2147483647
      # Upload the SARIF file generated in the previous step
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: results.sarif
      - name: Build Ionic project
        run: |
          ionic build --prod -- --base-href http://pedromrtaguilera.tech/
          cp www/index.html www/404.html
      - uses: actions/upload-artifact@v3
        with:
          name: www
          path: www/
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        if: contains(github.ref,'refs/heads/master')
        with:
          branch: gh-pages
          folder: www
          clean: true