name: Build and Deploy 

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: node:16

    steps:
      - name: Install git and rsync
        run: |
          apk update && apk add git rsync
        working-directory: ../
      - name: Configure git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global --add safe.directory /__w/peter-98.github.io/github-pages-deploy-action-temp-deployment-folder
        working-directory: ../
      - uses: actions/checkout@v2
      - name: Install Ionic
        run: npm install -g @ionic/cli
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - uses: stefanoeb/eslint-action@1.0.2
        with:
          files: src/
      - name: Run Codacy Analysis CLI
        run: |
          echo "CODACY_BASE_URL_OR_DEFAULT=\$(if [  ]; then echo ""; else echo "https://api.codacy.com"; fi)" >> $GITHUB_ENV
        shell: sh
      - name: Codacy Analysis CLI
        run: |
          npx codacy-analysis-cli analyze -t eslint -r results.json
        shell: sh
      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: Codacy Analysis Results
          path: results.json
      - name: Build Ionic project
        run: |
          ionic build --prod -- --base-href http://pedromrtaguilera.tech/
          cp www/index.html www/404.html
      - uses: actions/upload-artifact@v3
        with:
          name: www
          path: www/
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        if: contains(github.ref,'refs/heads/master')
        with:
          branch: gh-pages
          folder: www
          clean: true