name: Build and Deploy 

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: node:16-alpine

    steps:
      - name: Install git and rsync 📚
        run: |
          apk update && apk add git rsync
      - uses: actions/checkout@v2
      - name: Install Ionic
        run: npm install -g @ionic/cli
      - name: Install dependencies
        run: npm install
      - name: Build Ionic project
        run: |
          ionic build --prod
          cd www
          cp index.html 404.html
      - uses: actions/upload-artifact@v3
        with:
          name: www
          path: www/
      - name: List files
        run: ls -a
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: www
          clean: true